version: '3.3'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: 'mongo-teste'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: 'rabbitmq-teste'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
