server:
  port: 9083
  servlet:
    contextPath: /event-driven-api-sub1

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/event-driven-api?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    name:
      queue: event-driven-api-queue1
      exchange: event-driven-api-fanout

  application:
    name: event-driven-api-sub1